// Command gonc provides secure file encryption with support for deterministic
// and non-deterministic modes. It offers parallel processing capabilities and
// configurable file extensions for encrypted/decrypted outputs.
//
// Basic usage:
//
//	gonc [flags] command [flags] [paths...]
//
// The encryption key can be provided via command line flag or environment variable
// in hex-encoded format (32 or 64 bytes). Files can be encrypted with either
// standard (non-deterministic) or deterministic mode.
package main

import (
	"fmt"
	"os"

	"github.com/idelchi/gonc/internal/parse"
)

// version is the application version injected at build time.
var version = "unknown - unofficial & generated by unknown"

// main is the entry point of the application.
func main() {
	if err := parse.Execute(version); err != nil {
		fmt.Fprintln(os.Stderr, err)

		os.Exit(1)
	}

	os.Exit(0)
}
