// Command gonc ...
package main

import (
	"fmt"
	"os"

	"github.com/idelchi/gonc/internal/parse"
)

var version = "unknown - unofficial & generated by unknown"

// main initializes and runs the CLI application.
// It exits with code 1 if an error occurs.
func main() {
	if err := parse.Execute(version); err != nil {
		fmt.Fprintln(os.Stderr, err.Error())

		os.Exit(1)
	}
}
