package main

import (
	"fmt"
	"os"
	"runtime"
	"strings"

	"github.com/idelchi/gonc/internal/commands"
	"github.com/idelchi/gonc/internal/config"
	"github.com/spf13/viper"
)

var version = "unknown - unofficial & generated by unknown"

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	// Configure viper first
	viper.SetEnvPrefix("gonc")
	viper.SetEnvKeyReplacer(strings.NewReplacer(".", "_"))
	viper.AutomaticEnv()

	cfg := &config.Config{}

	root := commands.NewRootCmd(cfg)
	root.Version = version

	// Add persistent flags - they'll be automatically bound by viper
	root.Flags().StringP("key", "k", "", "Encryption key (64 or 32 bytes, hex-encoded)")
	root.Flags().IntP("parallel", "j", runtime.NumCPU(), "Number of parallel workers, defaults to number of CPUs")

	gen := commands.NewGenerateCmd(cfg)
	encrypt := commands.NewEncryptCmd(cfg)
	decrypt := commands.NewDecryptCmd(cfg)

	root.Flags().String("encrypt-ext", ".enc", "Suffix to append to encrypted files")
	root.Flags().String("decrypt-ext", "", "Suffix to append to decrypted files after removing the 'encrypt-ext' suffix")

	// gen.SetHelpFunc(func(command *cobra.Command, strings []string) {
	// 	// Hide flag for this command
	// 	// command.Flags().MarkHidden("key")
	// 	// command.Flags().MarkHidden("parallel")
	// 	// Call parent help func
	// 	command.Parent().HelpFunc()(command, strings)
	// })

	// Add commands
	root.AddCommand(
		gen,
		encrypt,
		decrypt,
	)

	root.Flags().SortFlags = false

	root.Flags().BoolP("deterministic", "d", false, "Use deterministic encryption mode")

	root.CompletionOptions.HiddenDefaultCmd = true

	return root.Execute()
}
