name: gonc

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - dev
      - main

jobs:
  info:
    uses: idelchi/devenv/.github/workflows/info.yml@main

  verify:
    uses: idelchi/devenv/.github/workflows/task.yml@main
    needs: info

  test:
    needs: verify
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - windows-2022
    runs-on: ${{ matrix.os }}
    env:
      GOGEN_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"
          check-latest: true

      - name: Test
        shell: sh
        run: |
          export PATH=~/.local/bin:$PATH
          echo "Added '~/.local/bin' to PATH"
          curl -sSL https://raw.githubusercontent.com/idelchi/gogen/refs/heads/dev/install.sh | sh -s -- -d ~/.local/bin
          ./tests/gonc-deterministic.sh
          ./tests/gonc-indeterministic.sh
